version: "3.7"
services:
    orthanc:
        image: jodogne/orthanc:latest
        restart: unless-stopped
        ports:
            - "8033:8042"
            - "4033:4242"
        environment:
            - KWDM_ENDPOINT=http://kwdmqueue:5555/queue/
        volumes:
            - ./dane/:/var/lib/orthanc/db/
            - ./konfiguracja/:/etc/orthanc/
        depends_on:
            - kwdmqueue
    kwdmqueue:
        build:
            context: ./kwdm
            dockerfile: ./Dockerfile.wp
        environment:
            - PORT=5555
            - ORTHANC_URI=http://orthanc:8042
            - DB=/db/queue.sql
        ports:
            - "8133:5555"
        volumes:
            - ./db:/db/
    kwdmworker:
        build:
            context: ./kwdmworker
            dockerfile: ./Dockerfile.wp
        environment:
            - QUEUE_URI=http://kwdmqueue:5555/queue/
            - ORTHANC_USER=orthanc
            - ORTHANC_PASSWORD=orthanc
        depends_on:
            - kwdmqueue


